### ISSUE TITLE
RuntimeError: Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow.

### ISSUE THREAD

**Issue by Tian14267** [cinastanbean/pytorch-onnx-tensorflow-pb#3]
onnx转pb模型的时候，报这个错误：
Traceback (most recent call last):
  File "onnx2pb.py", line 45, in <module>
    onnx2pb_2(onnx_input_path)
  File "onnx2pb.py", line 14, in onnx2pb_2
    tf_rep = prepare(model)
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/backend.py", line 66, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/backend.py", line 86, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/backend.py", line 147, in _onnx_graph_to_tensorflow_rep
    strict=strict)
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/backend.py", line 252, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/handlers/handler.py", line 59, in handle
    cls.args_check(node, **kwargs)
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/handlers/backend/resize.py", line 89, in args_check
    "Tensorflow")
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/common/exception.py", line 49, in __call__
    raise self._func(self.get_message(op, framework))
RuntimeError: Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow.
请问这个问题该怎么解决啊

**Comment by juzigithub** [comment]
How did you solve it in the end? I also encountered the same problem

**Comment by Ankur-singh** [comment]
I am facing the same issue. Did anyone find the solution ?
